#!/bin/sh

# FGB
# Simon H Moore
# 
# Checkout to chosen git branch using fzf

# Get list of branches
branches=$(git --no-pager branch -vv) &&

# choose branch using fzf
branch=$(echo "$branches" | fzf +m --preview="git diff ...{1}") &&

# checkout branch
git checkout $(echo "$branch" | awk '{print $1}' | sed "s/.* //")

