#!/bin/sh

# FV
# Simon H Moore
#
# Find files and open them in vim
# You can choose max depth of directory in first argument.
# Default max depth is 5.

get_files(){
    if command -v fd > /dev/null; then
        fd . -d "$depth" -t f
    else
        find ./ -maxdepth "$depth" -name .git -prune -o -type f -print 2>/dev/null
    fi
}

[ $1 ] && depth="$1" || depth="5"

files=$(get_files)

choice="$(echo "$files" | fzf --preview='cat {}' --preview-window=up:60%:wrap)" || exit

${EDITOR:-vim} "$choice"
